export const mType = {
  MODAL_TOGGLE      : 'MODAL_TOGGLE',
  UPDATE_UI         : 'UPDATE_UI',

  ITEM_ADD          : 'ITEM_ADD',
  ITEM_DEL          : 'ITEM_DEL',
  ITEM_PROCESS      : 'ITEM_PROCESS',
  ITEM_UPD_STATUS   : 'ITEM_UPD_STATUS',

  DB_INCR_UIID      : 'DB_INCR_UIID',
  API_REQ_HIBP      : 'API_REQ_HIBP',

  CD_START          : 'CD_START',
  CD_STOP           : 'CD_STOP',
  CD_INTERVAL_CHECKS: 'CD_INTERVAL_CHECKS',
  CD_SETTIMEOUT     : 'CD_SETTIMEOUT',
  CD_EA_EMAIL       : 'CD_EA_EMAIL',

  REQUEST_EA_EMAIL  : 'REQUEST_EA_EMAIL',
  EMAILS_CHECK_ALL  : 'EMAILS_CHECK_ALL',
}