export const mType = {
  MODAL_TOGGLE   : 'MODAL_TOGGLE',

  ITEM_ADD       : 'ITEM_ADD',
  ITEM_DEL       : 'ITEM_DEL',
  ITEM_PROCESS   : 'ITEM_PROCESS',
  ITEM_UPD_STATUS: 'ITEM_UPD_STATUS',

  DB_INCR_UIID   : 'DB_INCR_UIID',
  DB_DECR_UIID   : 'DB_DECR_UIID',
}